uploads = []
generated = []

[[outputs]]
id = "hhG0BBRF7_sDmhJFBH28z"
uri = "file://skysms-frontend-cloudflare-pages.tar.gz"
type = "unspecified"
title = "Frontend (Cloudflare Pages)"

[[outputs]]
id = "_bBTpSjdixFP0JZhXMdOq"
uri = "file://skysms-api-server-nodejs.tar.gz"
type = "unspecified"
title = "API Server (Node.js Host)"
